### ISSUE TITLE
lesson4-integration-with-actors.ipynb and lesson5-more-complex-graphs.ipynb invalid

### ISSUE THREAD

**Issue by PugachA** [Aaronontheweb/intro-to-akka.net-streams#11]
lesson4-integration-with-actors.ipynb and lesson5-more-complex-graphs.ipynb files don't open on github.

Please check files.

**Comment by Aaronontheweb** [comment]
I'll take a look!

**Comment by Aaronontheweb** [comment]
Yeah doesn't look like it - I wonder if this is an issue with cached output

**Comment by Aaronontheweb** [comment]
Going to see if upgrading to a new version of .NET Interactive here will help

**Comment by Aaronontheweb** [comment]
This has been resolved - re-running everything with the latest .NET Interactive did the trick.
